# Generated by Django 5.2.1 on 2025-05-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='noti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descri', models.TextField()),
                ('img', models.FileField(upload_to='')),
                ('ckeck', models.BooleanField(default=False)),
            ],
        ),
    ]
