# Generated by Django 5.2.1 on 2025-05-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notices', '0002_noti_upadated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noti',
            old_name='upadated',
            new_name='updated',
        ),
    ]
