# Generated by Django 5.2 on 2025-05-29 10:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notices', '0003_rename_upadated_noti_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noti',
            name='updated',
        ),
        migrations.AddField(
            model_name='noti',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
